const resourceOrder = ["species", "conopeptides", "biomarkers", "publications", "taxonomy", "archive", "datasetLogs"];

export const adminResources = {
    species: {
        table: "species",
        idColumn: "species_id",
        label: "Species",
        columns: [
            "species_id",
            "scientific_name",
            "common_name",
            "subgenus",
            "class_name",
            "order_name",
            "family_name",
            "genus_name",
            "province",
            "municipality",
            "num_conopeptides",
            "diet_type",
            "sequencing_platform",
            "tissue_source",
            "raw_data_in_ncbi_sra",
            "shell_image",
            "project",
            "doi",
            "status",
        ],
        required: ["species_id", "scientific_name", "common_name"],
        searchable: ["species_id", "scientific_name", "common_name", "province", "municipality", "subgenus"],
        importAliases: {
            "Species ID": "species_id",
            "Scientific name": "scientific_name",
            "Common name": "common_name",
            "Subgenus": "subgenus",
            "Class": "class_name",
            "Order": "order_name",
            "Family": "family_name",
            "Genus": "genus_name",
            "Province": "province",
            "Municipality": "municipality",
            "Number of conopeptides": "num_conopeptides",
            "Diet type": "diet_type",
            "Sequencing platform": "sequencing_platform",
            "Tissue source": "tissue_source",
            "Raw data in NCBI SRA": "raw_data_in_ncbi_sra",
            "Shell image": "shell_image",
            "Project": "project",
            "DOI": "doi",
            "Status": "status",
        },
        types: {
            num_conopeptides: "number",
            raw_data_in_ncbi_sra: "boolean",
        },
    },
    conopeptides: {
        table: "conopeptide",
        idColumn: "accession",
        label: "Conopeptides",
        columns: [
            "accession",
            "species_id",
            "species_name",
            "superfamily",
            "framework",
            "predicted_peptide",
            "matched_toxin",
            "precursor_sequence",
            "signal_peptide",
            "propeptide_sequence",
            "mature_peptide_sequence",
            "post_peptide_sequence",
            "remarks_sequence",
            "doi",
            "percent_similarity",
            "source_percent_similarity",
            "expression_value",
            "precursor_length",
            "mature_length",
            "num_cysteine_residues",
            "cysteine_pattern",
            "cysteine_framework",
        ],
        required: ["accession", "species_id", "species_name"],
        searchable: ["accession", "species_id", "species_name", "superfamily", "framework", "doi"],
        types: {
            percent_similarity: "number",
            expression_value: "number",
            precursor_length: "number",
            mature_length: "number",
            num_cysteine_residues: "number",
        },
    },
    biomarkers: {
        table: "biomarker",
        idColumn: "biomarker_id",
        label: "Biomarkers",
        columns: [
            "biomarker_id",
            "species_id",
            "species_name",
            "marker_type",
            "province",
            "municipality",
            "accession",
            "sequence_length",
            "sequence",
            "source_method",
            "sequence_database",
            "validation_status",
            "publication_doi",
        ],
        required: ["biomarker_id", "species_name"],
        searchable: ["biomarker_id", "species_id", "species_name", "marker_type", "province", "accession"],
        types: {
            sequence_length: "number",
        },
    },
    publications: {
        table: "publication",
        idColumn: "publication_id",
        label: "Publications",
        columns: [
            "publication_id",
            "title",
            "authors",
            "year_published",
            "journal",
            "doi",
            "evidence_type",
            "linked_species",
            "linked_conopeptides",
            "linked_biomarkers",
            "province",
            "status",
        ],
        required: ["publication_id", "title"],
        searchable: ["publication_id", "title", "authors", "year_published", "journal", "doi"],
        types: {
            linked_species: "number",
            linked_conopeptides: "number",
            linked_biomarkers: "number",
        },
    },
    taxonomy: {
        table: "taxonomy",
        idColumn: "species_id",
        label: "Taxonomy",
        columns: [
            "species_id",
            "scientific_name",
            "common_name",
            "class_name",
            "order_name",
            "family_name",
            "genus_name",
            "subgenus",
            "organisms_diet",
            "anatomical_sample",
            "tissue_source",
        ],
        required: ["species_id", "scientific_name", "common_name"],
        searchable: ["species_id", "scientific_name", "common_name", "class_name", "family_name", "genus_name"],
        types: {},
    },
    archive: {
        table: "admin_archive",
        idColumn: "archive_id",
        label: "Archive",
        readOnly: true,
        columns: [
            "archive_id",
            "resource_name",
            "record_id",
            "record_data",
            "archived_at",
            "archived_by",
        ],
        required: ["archive_id", "resource_name", "record_id"],
        searchable: ["archive_id", "resource_name", "record_id", "archived_by"],
        types: {},
    },
    datasetLogs: {
        table: "dataset_import_logs",
        idColumn: "log_id",
        label: "Dataset Logs",
        readOnly: true,
        columns: [
            "log_id",
            "resource_name",
            "original_filename",
            "imported_row_count",
            "created_count",
            "updated_count",
            "skipped_count",
            "status",
            "notes",
            "imported_by",
            "imported_at",
        ],
        required: ["log_id", "resource_name"],
        searchable: ["log_id", "resource_name", "original_filename", "status", "notes", "imported_by"],
        types: {
            imported_row_count: "number",
            created_count: "number",
            updated_count: "number",
            skipped_count: "number",
        },
    },
};

export function getAdminResource(resourceName) {
    return adminResources[resourceName] ?? null;
}

export function getOrderedAdminResourceEntries() {
    return resourceOrder.map((key) => [key, adminResources[key]]).filter(([, resource]) => Boolean(resource));
}
