const resourceOrder = ["species", "conopeptides", "biomarkers", "publications", "taxonomy", "archive", "datasetLogs"];

export const adminResources = {
    species: {
        table: "species",
        idColumn: "species_id",
        label: "Species",
        columns: [
            "species_id",
            "scientific_name",
            "common_name",
            "subgenus",
            "class_name",
            "order_name",
            "family_name",
            "genus_name",
            "province",
            "municipality",
            "num_conopeptides",
            "diet_type",
            "sequencing_platform",
            "tissue_source",
            "raw_data_in_ncbi_sra",
            "shell_image",
            "project",
            "doi",
            "status",
        ],
        required: ["species_id", "scientific_name", "common_name"],
        searchable: ["species_id", "scientific_name", "common_name", "province", "municipality", "subgenus"],
        importAliases: {
            "Species ID": "species_id",
            "Scientific name": "scientific_name",
            "Common name": "common_name",
            "Subgenus": "subgenus",
            "Class": "class_name",
            "Order": "order_name",
            "Family": "family_name",
            "Genus": "genus_name",
            "Province": "province",
            "Municipality": "municipality",
            "Number of conopeptides": "num_conopeptides",
            "Diet type": "diet_type",
            "Sequencing platform": "sequencing_platform",
            "Tissue source": "tissue_source",
            "Raw data in NCBI SRA": "raw_data_in_ncbi_sra",
            "Shell image": "shell_image",
            "Project": "project",
            "DOI": "doi",
            "Status": "status",
        },
        types: {
            num_conopeptides: "number",
            raw_data_in_ncbi_sra: "boolean",
        },
    },
    conopeptides: {
        table: "conopeptide",
        idColumn: "accession",
        label: "Conopeptides",
        columns: [
            "accession",
            "species_id",
            "species_name",
            "superfamily",
            "framework",
            "predicted_peptide",
            "matched_toxin",
            "precursor_sequence",
            "signal_peptide",
            "propeptide_sequence",
            "mature_peptide_sequence",
            "post_peptide_sequence",
            "remarks_sequence",
            "doi",
            "percent_similarity",
            "source_percent_similarity",
            "expression_value",
            "precursor_length",
            "mature_length",
            "num_cysteine_residues",
            "cysteine_pattern",
            "cysteine_framework",
        ],
        required: ["accession", "species_id", "species_name"],
        searchable: ["accession", "species_id", "species_name", "superfamily", "framework", "doi"],
        importAliases: {
            "Conopeptide ID": "accession",
            "Scientific name": "species_name",
            "Species ID": "species_id",
            "Precursor Sequence": "precursor_sequence",
            "Remarks for Sequence": "remarks_sequence",
            "Signal peptide": "signal_peptide",
            "Propeptide sequence": "propeptide_sequence",
            "Mature Peptide Sequence": "mature_peptide_sequence",
            "Post Peptide Sequence": "post_peptide_sequence",
            "Gene superfamily": "superfamily",
            "Matched Toxin": "matched_toxin",
            "Percent Similarity": "percent_similarity",
            "Source of Percent Similarity": "source_percent_similarity",
            "Expression Value": "expression_value",
            "DOI": "doi",
            "Length of Precursor Sequence": "precursor_length",
            "Length of Mature Conopeptides": "mature_length",
            "Number of Cysteine Residues": "num_cysteine_residues",
            "Cysteine Pattern": "cysteine_pattern",
            "Cysteine Framework": "cysteine_framework",
        },
        importDefaults: (data) => ({
            ...data,
            framework: data.framework || data.cysteine_framework || "",
            predicted_peptide: data.predicted_peptide || data.mature_peptide_sequence || "",
        }),
        types: {
            expression_value: "number",
            precursor_length: "number",
            mature_length: "number",
            num_cysteine_residues: "number",
        },
    },
    biomarkers: {
        table: "biomarker",
        idColumn: "biomarker_id",
        label: "Biomarkers",
        columns: [
            "biomarker_id",
            "species_id",
            "species_name",
            "marker_type",
            "province",
            "municipality",
            "accession",
            "sequence_length",
            "sequence",
            "source_method",
            "sequence_database",
            "validation_status",
            "publication_doi",
        ],
        required: ["biomarker_id", "species_name"],
        searchable: ["biomarker_id", "species_id", "species_name", "marker_type", "province", "accession"],
        importAliases: {
            "Species Name": "species_name",
            "Barcode ID": "biomarker_id",
            "Specimen ID": "biomarker_id",
            "Species ID": "species_id",
            "Gene Marker": "marker_type",
            "Province": "province",
            "Municipality": "municipality",
            "External Accession": "accession",
            "Sequence Length (bp)": "sequence_length",
            "Sequence": "sequence",
            "Source Method": "source_method",
            "Sequence Database": "sequence_database",
            "Validation Status of CO1 Sequences": "validation_status",
            "Publication DOI": "publication_doi",
        },
        importDefaults: (data) => ({
            ...data,
            marker_type: data.marker_type || "Unavailable",
            accession: data.accession || "Unavailable",
            validation_status: data.validation_status || "Unavailable",
        }),
        types: {
            sequence_length: "number",
        },
    },
    publications: {
        table: "publication",
        idColumn: "publication_id",
        label: "Publications",
        columns: [
            "publication_id",
            "title",
            "authors",
            "year_published",
            "journal",
            "doi",
            "evidence_type",
            "linked_species",
            "linked_conopeptides",
            "linked_biomarkers",
            "province",
            "status",
        ],
        required: ["publication_id", "title"],
        searchable: ["publication_id", "title", "authors", "year_published", "journal", "doi"],
        importAliases: {
            "Publication ID": "publication_id",
            "Title": "title",
            "Authors": "authors",
            "Year Published": "year_published",
            "Year": "year_published",
            "Journal": "journal",
            "DOI": "doi",
            "Evidence Type": "evidence_type",
            "Linked Species": "linked_species",
            "Linked Conopeptides": "linked_conopeptides",
            "Linked Biomarkers": "linked_biomarkers",
            "Province": "province",
            "Status": "status",
        },
        importDefaults: (data) => ({
            ...data,
            publication_id: data.publication_id || data.doi || data.title,
            linked_species: data.linked_species || 0,
            linked_conopeptides: data.linked_conopeptides || 0,
            linked_biomarkers: data.linked_biomarkers || 0,
        }),
        types: {
            linked_species: "number",
            linked_conopeptides: "number",
            linked_biomarkers: "number",
        },
    },
    taxonomy: {
        table: "taxonomy",
        idColumn: "species_id",
        label: "Taxonomy",
        columns: [
            "species_id",
            "scientific_name",
            "common_name",
            "class_name",
            "order_name",
            "family_name",
            "genus_name",
            "subgenus",
            "organisms_diet",
            "anatomical_sample",
            "tissue_source",
        ],
        required: ["species_id", "scientific_name", "common_name"],
        searchable: ["species_id", "scientific_name", "common_name", "class_name", "family_name", "genus_name"],
        importAliases: {
            "Species ID": "species_id",
            "Species": "scientific_name",
            "Scientific name": "scientific_name",
            "Common name": "common_name",
            "Class": "class_name",
            "Order": "order_name",
            "Family": "family_name",
            "Genus": "genus_name",
            "Subgenus": "subgenus",
            "Diet type": "organisms_diet",
            "Organisms Diet": "organisms_diet",
            "Anatomical Sample": "anatomical_sample",
            "Tissue source": "tissue_source",
        },
        importDefaults: (data) => ({
            ...data,
            common_name: data.common_name || data.scientific_name || "Unavailable",
        }),
        types: {},
    },
    archive: {
        table: "admin_archive",
        idColumn: "archive_id",
        label: "Archive",
        readOnly: true,
        columns: [
            "archive_id",
            "resource_name",
            "record_id",
            "record_data",
            "archived_at",
            "archived_by",
        ],
        required: ["archive_id", "resource_name", "record_id"],
        searchable: ["archive_id", "resource_name", "record_id", "archived_by"],
        types: {},
    },
    datasetLogs: {
        table: "dataset_import_logs",
        idColumn: "log_id",
        label: "Dataset Logs",
        readOnly: true,
        columns: [
            "log_id",
            "resource_name",
            "original_filename",
            "imported_row_count",
            "created_count",
            "updated_count",
            "skipped_count",
            "status",
            "notes",
            "imported_by",
            "imported_at",
        ],
        required: ["log_id", "resource_name"],
        searchable: ["log_id", "resource_name", "original_filename", "status", "notes", "imported_by"],
        types: {
            imported_row_count: "number",
            created_count: "number",
            updated_count: "number",
            skipped_count: "number",
        },
    },
};

export function getAdminResource(resourceName) {
    return adminResources[resourceName] ?? null;
}

export function getOrderedAdminResourceEntries() {
    return resourceOrder.map((key) => [key, adminResources[key]]).filter(([, resource]) => Boolean(resource));
}
